<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Create a 4 5 matrix of random integers between 20 and 80
arr = np.random.randint(20, 80, (4, 5))
print("Matrix of(4x5): ")
print(arr)

# Minimum and maximum value
min_value = np.min(arr)
max_value = np.max(arr)
print("\n1) Minimum value: ", min_value)
print("2) Maximum value: ", max_value)

# Sum of all elements
sum = np.sum(arr)
print("3) Sum of all elements: ", sum)

# Mean and Standard Deviation
m = np.mean(arr)
print("4) Mean: ", m)
std = np.std(arr)
print("5) Standard Deviation: ", std)

Matrix of(4x5): 
[[32 43 56 75 20]
 [78 77 48 31 39]
 [50 44 54 48 29]
 [29 72 37 29 54]]

1) Minimum value:  20
2) Maximum value:  78
3) Sum of all elements:  945
4) Mean:  47.25
5) Standard Deviation:  17.073005007906488
