<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/program_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
# Create a 2D array of shape 5, 6) filled with random integers between 10 and 100.
arr = np.random.randint(10, 101, (5, 6))

# print array
print("2D Array: ")
print(arr)

# prints details
print("\nShape: ", arr.shape)
print("Total number of elements: ", arr.size)
print("Data Type: ", arr.dtype)

2D Array: 
[[28 99 53 74 22 49]
 [77 43 78 40 74 27]
 [67 36 42 59 23 90]
 [12 29 89 11 35 90]
 [98 20 79 20 31 88]]

Shape:  (5, 6)
Total number of elements:  30
Data Type:  int64
