<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# Create a 4 5 matrix of random integers between 20 and 80
arr = np.random.randint(20, 80, (4, 5))
print("Matrix of(4x5): ")
print(arr)

# Minimum and maximum value
min_value = np.min(arr)
max_value = np.max(arr)
print("\n1) Minimum value: ", min_value)
print("2) Maximum value: ", max_value)

# Sum of all elements
sum = np.sum(arr)
print("3) Sum of all elements: ", sum)

# Mean and Standard Deviation
m = np.mean(arr)
print("4) Mean: ", m)
std = np.std(arr)
print("5) Standard Deviation: ", std)

# sum of each row
print("\n6) Sum of each row: ", np.sum(arr, axis=1))

# sum of each column
print("7) Sum of each column: ", np.sum(arr, axis=0))

Matrix of(4x5): 
[[62 64 36 78 57]
 [42 38 31 64 67]
 [30 56 41 47 75]
 [36 75 62 58 62]]

1) Minimum value:  30
2) Maximum value:  78
3) Sum of all elements:  1081
4) Mean:  54.05
5) Standard Deviation:  14.864302876354479

6) Sum of each row:  [297 242 249 293]
7) Sum of each column:  [170 233 170 247 261]
