<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Generate a 6x6 matrix of random numbers
matrix = np.random.randn(6, 6)

# Print the matrix
print("Original Matrix:")
print(matrix)

# Print shape, size, and data type
print("\nShape:", matrix.shape)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

# Find the index of the maximum and minimum value
print("\nIndex of Maximum Value:", np.argmax(matrix))
print("Index of Minimum Value:", np.argmin(matrix))

# Extract the top-left 3x3 submatrix
print("\nTop-Left 3x3 Submatrix:")
print(matrix[:3, :3])

# Replace all negative numbers with their absolute value
matrix[matrix < 0] = np.abs(matrix[matrix < 0])

# Print the modified matrix
print("\nModified Matrix:")
print(matrix)

# Print the mean of the modified matrix
print("\nMean of Modified Matrix:")
print(np.mean(matrix))

Original Matrix:
[[ 0.87414139 -1.67260604 -0.04880091  1.87387448  0.02278158  0.09033514]
 [-1.94967356 -1.01244226 -0.75949701  1.10578716 -1.62517631  0.34034524]
 [ 1.72992169 -0.48883634  0.10352023 -0.40900116  0.15457351  0.49690462]
 [ 0.11619511  1.03834064 -1.59478326  0.59572014  0.47308265 -0.25808283]
 [ 1.67377399  0.0058474   0.71522984 -0.89234102 -0.47987792 -0.52198443]
 [-0.10100706  0.17871077 -0.41277727 -0.49399674  0.82193608 -1.39879107]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: 3
Index of Minimum Value: 6

Top-Left 3x3 Submatrix:
[[ 0.87414139 -1.67260604 -0.04880091]
 [-1.94967356 -1.01244226 -0.75949701]
 [ 1.72992169 -0.48883634  0.10352023]]

Modified Matrix:
[[0.87414139 1.67260604 0.04880091 1.87387448 0.02278158 0.09033514]
 [1.94967356 1.01244226 0.75949701 1.10578716 1.62517631 0.34034524]
 [1.72992169 0.48883634 0.10352023 0.40900116 0.15457351 0.49690462]
 [0.11619511 1.03834064 1.59478326 0.59572014 0.47308265 0.25808283]