<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("2D Array: ")
print(arr)

# Extract first row
print("\nFrist row: ")
print(arr[0])

# Extract last column
print("\nLast column: ")
print(arr[:, 3])

# Extract center 2x2 submatrix
print("\nCenter 2x2 submatrix: ")
print(arr[1:3, 1:3])

# Extract all even numbers from the array using boolean indexing
print("\nEven numbers: ")
print(arr[arr % 2 == 0])

2D Array: 
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Frist row: 
[10 20 30 40]

Last column: 
[ 40  80 120]

Center 2x2 submatrix: 
[[ 60  70]
 [100 110]]

Even numbers: 
[ 10  20  30  40  50  60  70  80  90 100 110 120]
