<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate a 2D array of shape (10, 5) with random marks between 30 and 100
marks = np.random.randint(30, 101, (10, 5))

print("=== Student Marks Analyzer ===")
# Print the marks array
print("\nStudent Marks (10 Students × 5 Subjects):")
print(marks)

# Calculate total marks of each student
total = np.sum(marks, axis=1)
print("\nTotal Marks of Each Student:")
print(total)

# Calculate average marks of each student
average = np.mean(marks, axis=1)
print("\nAverage Marks of Each Student:")
print(average)

# Find the student with highest total marks
highest = np.argmax(total)
print("\nStudent with Highest Total Marks:", highest)
print("Highest Total Marks:", total[highest])

# Find the student with lowest total marks
lowest = np.argmin(total)
print("\nStudent with Lowest Total Marks:", lowest)
print("Lowest Total Marks:", total[lowest])

# Calculate overall class mean
class_mean = np.mean(marks)
print("\nOverall Class Mean:", class_mean)

# Calculate overall class standard deviation
class_std = np.std(marks)
print("Overall Class Standard Deviation:", class_std)

# Reshape the array into 5 × 10
reshaped = marks.reshape(5, 10)
print("\nReshaped Array (5 × 10):")
print(reshaped)

# Find the indices of the top 3 students based on total marks
top3 = np.argsort(total)[-3:][::-1]

# Extract marks of the top 3 students
print("\nTop 3 Students' Marks:")
print(marks[top3])

=== Student Marks Analyzer ===

Student Marks (10 Students × 5 Subjects):
[[ 74  30  87  91  91]
 [ 31  62 100  64  32]
 [ 31  91 100  91  52]
 [ 77  79  42  93  51]
 [ 58  37  57  78  74]
 [ 69  71  30  41  59]
 [ 66  70  63  92  64]
 [ 48  47  71  33  33]
 [ 74  90  49  78  41]
 [ 73  85  84  69  74]]

Total Marks of Each Student:
[373 289 365 342 304 270 355 232 332 385]

Average Marks of Each Student:
[74.6 57.8 73.  68.4 60.8 54.  71.  46.4 66.4 77. ]

Student with Highest Total Marks: 9
Highest Total Marks: 385

Student with Lowest Total Marks: 7
Lowest Total Marks: 232

Overall Class Mean: 64.94
Overall Class Standard Deviation: 20.733943185028746

Reshaped Array (5 × 10):
[[ 74  30  87  91  91  31  62 100  64  32]
 [ 31  91 100  91  52  77  79  42  93  51]
 [ 58  37  57  78  74  69  71  30  41  59]
 [ 66  70  63  92  64  48  47  71  33  33]
 [ 74  90  49  78  41  73  85  84  69  74]]

Top 3 Students' Marks:
[[ 73  85  84  69  74]
 [ 74  30  87  91  91]
 [ 31  91 100  91  52]]
