<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Create a 1D array containing numbers from 1 to 24 using np.arange()
a = np.arange(1, 25)
arr = np.array(a)

print("1) Original 1D Array: ")
print(arr)
print("Shape: ", arr.shape)

# Reshape it into (4, 6)
arr2 = np.array(a).reshape(4, 6)
print("\n2) Reshaped 2D Array: ")
print(arr2)
print("Shape: ", arr2.shape)

# Reshape it into (3, 8)
arr3 = np.array(a).reshape(3, 8)
print("\n3) Reshaped 2D Array: ")
print(arr3)
print("Shape: ", arr3.shape)

# Reshape it into (2, 3, 4)
arr4 = np.array(a).reshape(2, 3, 4)
print("\n4) Reshaped 3D Array: ")
print(arr4)
print("Shape: ", arr4.shape)



1) Original 1D Array: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape:  (24,)

2) Reshaped 2D Array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape:  (4, 6)

3) Reshaped 2D Array: 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape:  (3, 8)

4) Reshaped 3D Array: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape:  (2, 3, 4)
