<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#Create two 3x3 matrices:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[9,8,7], [6,5,4], [3,2,1]])

print("2D Array: ")
print("A =", A)
print("B =", B)

# Element-wise multiplication
print("\n1) Element-wise multiplication: ")
print(A * B)

# Matrix multiplication
print("\n2) Matrix multiplication: ")

# 1)  Using np.dot()
print("\nUsing np.dot(): ")
print(np.dot(A, B))

# 2)  Using  @ operator
print("\nUsing  @ operator: ")
print(A @ B)

Difference:
"""
1. Element-wise Multiplication (*) multiplies corresponding elements
   of the two matrices.

2. Matrix Multiplication (@ or np.dot()) follows the row × column rule,
   where each element of the result is obtained by multiplying a row of
   the first matrix with a column of the second matrix. """


2D Array: 
A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[9 8 7]
 [6 5 4]
 [3 2 1]]

1) Element-wise multiplication: 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

2) Matrix multiplication: 

Using np.dot(): 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Using  @ operator: 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
