<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("1D Array: ")
print("a = ", a)
print("b = ", b)

# Addition
print("\n1) Addition: ")
print(a + b)

# Subtraction
print("\n2) Subtraction: ")
print(a - b)

# Multiplication
print("\n3) Multiplication: ")
print(a * b)

# Division
print("\n4) Division: ")
print(a / b)

# Element-wise power
print("\n5) Element-wise power: ")
print(a ** b)

# Modulo operation %
print("\n6) Modulo operation: ")
print(a % b)


1D Array: 
a =  [10 20 30 40]
b =  [1 2 3 4]

1) Addition: 
[11 22 33 44]

2) Subtraction: 
[ 9 18 27 36]

3) Multiplication: 
[ 10  40  90 160]

4) Division: 
[10. 10. 10. 10.]

5) Element-wise power: 
[     10     400   27000 2560000]

6) Modulo operation: 
[0 0 0 0]
