<a href="https://colab.research.google.com/github/aryac-2006/Numpy-project-02/blob/main/Program_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 5x5 matrix of random integers between 1 and 100
arr = np.random.randint(1, 100, (5,5))
print("Original Array: ")
print(arr)

# Print the diagonal elements
print("\nDiagonal Element: ")
print(np.diag(arr))

# Print elements greater than 50
print("\nElements greater than 50: ")
print(arr[arr > 50])

# Replace all elements less than 30 with 0
arr[ arr < 30] == 0

#Print the modified array
print("\nModified Array: ")
print(arr)

Original Array: 
[[12 28 12 33 10]
 [28 15 57 15 82]
 [51 76 15 42 27]
 [43 28  1 93 73]
 [37 30 51 90 69]]

Diagonal Element: 
[12 15 15 93 69]

Elements greater than 50: 
[57 82 51 76 93 73 51 90 69]

Modified Array: 
[[12 28 12 33 10]
 [28 15 57 15 82]
 [51 76 15 42 27]
 [43 28  1 93 73]
 [37 30 51 90 69]]
